# Default values for central-logging.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

#central-fluentd:
#  replicas: 1

elasticsearch:
  master_replicas: 1
  data_replicas: 1
  persistence:
    enabled: false

#kafka:
#  replicas: 1
#  image: quay.io/samsung_cnct/kafka-statefulset:latest
#  persistence:
#    enabled: false
#  kafka_monitor_service_type: ClusterIP

kibana:
  replicas: 1
  service:
    type: ClusterIP
